### ISSUE TITLE
문제

### ISSUE THREAD

**Issue by juny2059** [XxPKBxX/gen#1]

**Comment by juny2059** [comment]
문제가 있어요.
초가 다 지나고 알겠어요를 누를때 마우스가 없어져요 
해결해 주세요~!

**Comment by XxPKBxX** [comment]
CPS 측정 시 마우스가 사라지는 것은 기능입니다. 마우스가 브라우저 밖으로 나가지 않게 합니다.
마우스를 보이려면 ESC 키를 눌러주세요.
